-- MySQL Script generated by MySQL Workbench
-- Tue Mar  9 11:37:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GreenIT
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GreenIT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GreenIT` DEFAULT CHARACTER SET utf8 ;
USE `GreenIT` ;

-- -----------------------------------------------------
-- Table `GreenIT`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenIT`.`article` (
  `idArticle` INT NOT NULL AUTO_INCREMENT,
  `nameArticle` VARCHAR(100) NOT NULL,
  `prixArticle` VARCHAR(100) NOT NULL,
  `image1` BLOB NULL,
  `image2` BLOB NULL,
  `image3` BLOB NULL,
  `image4` BLOB NULL,
  `image5` BLOB NULL,
  PRIMARY KEY (`idArticle`),
  UNIQUE INDEX `idArticle_UNIQUE` (`idArticle` ASC),
  UNIQUE INDEX `nameArticle_UNIQUE` (`nameArticle` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenIT`.`panier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenIT`.`panier` (
  `idPanier` INT NOT NULL AUTO_INCREMENT,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`idPanier`),
  UNIQUE INDEX `idPanier_UNIQUE` (`idPanier` ASC),
  INDEX `fk_panier_article1_idx` (`article_idArticle` ASC),
  CONSTRAINT `fk_panier_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `GreenIT`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenIT`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenIT`.`comment` (
  `idComment` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`idComment`),
  UNIQUE INDEX `idComment_UNIQUE` (`idComment` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenIT`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenIT`.`post` (
  `IDpost` INT NOT NULL AUTO_INCREMENT,
  `typePost` VARCHAR(100) NOT NULL,
  `date` DATETIME NOT NULL,
  `time` DATETIME NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `numeroTelephone` INT NOT NULL,
  `addresse` VARCHAR(250) NOT NULL,
  `comment_idComment` INT NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`IDpost`),
  UNIQUE INDEX `IDpost_UNIQUE` (`IDpost` ASC),
  INDEX `fk_post_comment1_idx` (`comment_idComment` ASC),
  INDEX `fk_post_article1_idx` (`article_idArticle` ASC),
  CONSTRAINT `fk_post_comment1`
    FOREIGN KEY (`comment_idComment`)
    REFERENCES `GreenIT`.`comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `GreenIT`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenIT`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenIT`.`User` (
  `IDUser` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `panier_idPanier` INT NOT NULL,
  `comment_idComment` INT NOT NULL,
  `post_IDpost` INT NOT NULL,
  PRIMARY KEY (`IDUser`),
  UNIQUE INDEX `IDUser_UNIQUE` (`IDUser` ASC),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  INDEX `fk_User_panier_idx` (`panier_idPanier` ASC),
  INDEX `fk_User_comment1_idx` (`comment_idComment` ASC),
  INDEX `fk_User_post1_idx` (`post_IDpost` ASC),
  CONSTRAINT `fk_User_panier`
    FOREIGN KEY (`panier_idPanier`)
    REFERENCES `GreenIT`.`panier` (`idPanier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_comment1`
    FOREIGN KEY (`comment_idComment`)
    REFERENCES `GreenIT`.`comment` (`idComment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_post1`
    FOREIGN KEY (`post_IDpost`)
    REFERENCES `GreenIT`.`post` (`IDpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GreenIT`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GreenIT`.`categorie` (
  `IDcategorie` INT NOT NULL AUTO_INCREMENT,
  `typeCategorie` VARCHAR(100) NOT NULL,
  `nameCategorie` VARCHAR(100) NOT NULL,
  `article_idArticle` INT NOT NULL,
  PRIMARY KEY (`IDcategorie`),
  UNIQUE INDEX `IDcategorie_UNIQUE` (`IDcategorie` ASC),
  UNIQUE INDEX `typeCategorie_UNIQUE` (`typeCategorie` ASC),
  UNIQUE INDEX `nameCategorie_UNIQUE` (`nameCategorie` ASC),
  INDEX `fk_categorie_article1_idx` (`article_idArticle` ASC),
  CONSTRAINT `fk_categorie_article1`
    FOREIGN KEY (`article_idArticle`)
    REFERENCES `GreenIT`.`article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
