-- MySQL Script generated by MySQL Workbench
-- Tue Mars 09 11:29:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema intmarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema intmarket
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `greenIT` ;
CREATE SCHEMA `greenIT` ;
USE `greenIT` ;

-- -----------------------------------------------------
-- Table `greenIT`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE `greenIT`.`utilisateur` (
                                         `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
                                         `nom` VARCHAR(100) NOT NULL,
                                         `prenom` VARCHAR(100) NOT NULL,
                                         `mail` VARCHAR(100) NOT NULL,
                                         `mdp` VARCHAR(100) NOT NULL,
                                         `addresse` VARCHAR(100) NOT NULL,
                                         `panier` VARCHAR(250) NOT NULL,
                                         `role` VARCHAR(100) NULL,
                                         PRIMARY KEY (`idUtilisateur`),
                                         UNIQUE INDEX `idUtilisateur_UNIQUE` (`idUtilisateur` ASC) ,
                                         UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenIT`.`categorie`
-- -----------------------------------------------------
CREATE TABLE `greenIT`.`categorie` (
                                       `idCategorie` INT NOT NULL AUTO_INCREMENT,
                                       `nomCategoriecol` VARCHAR(100) NOT NULL,
                                       `sousCategorie` VARCHAR(100) NOT NULL,
                                       PRIMARY KEY (`idCategorie`),
                                       UNIQUE INDEX `idCategorie_UNIQUE` (`idCategorie` ASC) )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenIT`.`article`
-- -----------------------------------------------------
CREATE TABLE `greenIT`.`article` (
                                     `idArticle` INT NOT NULL AUTO_INCREMENT,
                                     `nomArticle` VARCHAR(100) NOT NULL,
                                     `prixArticle` VARCHAR(100) NOT NULL,
                                     `imageArticle` VARCHAR(100) NOT NULL,
                                     `descriptionArticle` VARCHAR(100) NOT NULL,
                                     `quantite` INT NOT NULL,
                                     `categorie_idCategorie` INT NOT NULL,
                                     PRIMARY KEY (`idArticle`),
                                     UNIQUE INDEX `idArticle_UNIQUE` (`idArticle` ASC) ,
                                     UNIQUE INDEX `imageArticle_UNIQUE` (`imageArticle` ASC) ,
                                     INDEX `fk_article_categorie1_idx` (`categorie_idCategorie` ASC) ,
                                     CONSTRAINT `fk_article_categorie1`
                                         FOREIGN KEY (`categorie_idCategorie`)
                                             REFERENCES `intmarket`.`categorie` (`idCategorie`)
                                             ON DELETE NO ACTION
                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenIT`.`commande`
-- -----------------------------------------------------
CREATE TABLE `greenIT`.`commande` (
                                      `idCommande` INT NOT NULL AUTO_INCREMENT,
                                      `dateCommande` DATE NOT NULL,
                                      `utilisateur_idUtilisateur` INT NOT NULL,
                                      `article_idArticle` INT NOT NULL,
                                      PRIMARY KEY (`idCommande`),
                                      UNIQUE INDEX `idCommande_UNIQUE` (`idCommande` ASC) ,
                                      INDEX `fk_commande_utilisateur1_idx` (`utilisateur_idUtilisateur` ASC) ,
                                      INDEX `fk_commande_article1_idx` (`article_idArticle` ASC) ,
                                      CONSTRAINT `fk_commande_utilisateur1`
                                          FOREIGN KEY (`utilisateur_idUtilisateur`)
                                              REFERENCES `intmarket`.`utilisateur` (`idUtilisateur`)
                                              ON DELETE NO ACTION
                                              ON UPDATE NO ACTION,
                                      CONSTRAINT `fk_commande_article1`
                                          FOREIGN KEY (`article_idArticle`)
                                              REFERENCES `intmarket`.`article` (`idArticle`)
                                              ON DELETE NO ACTION
                                              ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greenIT`.`ligneCommande`
-- -----------------------------------------------------
CREATE TABLE `greenIT`.`ligneCommande` (
                                           `facture` DECIMAL(6,2) NOT NULL,
                                           `quantite` DECIMAL(3,0) NOT NULL,
                                           `commande_idCommande` INT NOT NULL,
                                           `article_idArticle` INT NOT NULL,
                                           INDEX `fk_ligneCommande_commande1_idx` (`commande_idCommande` ASC) ,
                                           INDEX `fk_ligneCommande_article1_idx` (`article_idArticle` ASC) ,
                                           CONSTRAINT `fk_ligneCommande_commande1`
                                               FOREIGN KEY (`commande_idCommande`)
                                                   REFERENCES `intmarket`.`commande` (`idCommande`)
                                                   ON DELETE NO ACTION
                                                   ON UPDATE NO ACTION,
                                           CONSTRAINT `fk_ligneCommande_article1`
                                               FOREIGN KEY (`article_idArticle`)
                                                   REFERENCES `intmarket`.`article` (`idArticle`)
                                                   ON DELETE NO ACTION
                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
